const lorem = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi
doloremque fuga obcaecati facere, enim quisquam, temporibus optio
ducimus magni aliquam nulla. Eligendi officia eaque nesciunt facilis
quia consectetur totam non.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi
doloremque fuga obcaecati facere, enim quisquam, temporibus optio
ducimus magni aliquam nulla. Eligendi officia eaque nesciunt facilis
quia consectetur totam non.`;

const mentors = [
  {
    section: "gh-section",
    country: "Ghana",
    mentors: [
      {
        name: "Samuel Opoku Agyemang",
        job: "Software Engineer",
        company: "Slack",
        email: "sam@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=51",
        bio: lorem,
      },
      {
        name: "Charles Opoku Agyemang",
        job: "Software Developer",
        company: "Slack",
        bio: lorem,
        email: "sam@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=64",
      },
      {
        name: "Tahiru Abdullai",
        job: "Mobile App Developer",
        company: "Slack",
        bio: lorem,
        email: "sam@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=68",
      },
      {
        name: "Faddal Ibrahim",
        job: "Full Stack Developer",
        company: "Slack",
        bio: lorem,
        email: "faddal@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=7",
      },
      {
        name: "Assan Ewudzi Nathaniel",
        job: "Full Stack Developer",
        company: "Slack",
        bio: lorem,
        email: "assan@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=70",
      },
    ],
  },
  {
    section: "mu-section",
    country: "Mauritius",
    mentors: [
      {
        name: "Mani Riaz",
        job: "Full Stack Engineer",
        company: "Slack",
        bio: lorem,
        email: "mani@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=69",
      },
      {
        name: "Sania Sooraj",
        job: "Software Developer",
        company: "Slack",
        bio: lorem,
        email: "mani@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=67",
      },
      {
        name: "Sharon Ramgoolam",
        job: "Mobile App Developer",
        company: "Slack",
        bio: lorem,
        email: "shaRamgoo@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=43",
      },
      {
        name: "Raychel Soulayman",
        job: "Full Stack Developer",
        company: "Slack",
        bio: lorem,
        email: "SoulayRay@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=35",
      },
      {
        name: "Fabrice Bilaal",
        job: "Full Stack Developer",
        company: "Slack",
        bio: lorem,
        email: "fabilaal@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=17",
      },
    ],
  },
  {
    section: "uk-section",
    country: "United Kingdom",
    mentors: [
      {
        name: "Elizabeth Breadington",
        job: "Software Engineer",
        company: "Slack",
        bio: lorem,
        email: "mani@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=27",
      },
      {
        name: "Brood Washington",
        job: "Software Developer",
        company: "Slack",
        bio: lorem,
        email: "mani@gmail.com",
        phone: "+233 456 789 43",
        website: "saniaoffice.website.com",
        pic: "https://i.pravatar.cc/400?img=3",
      },
      {
        name: "Heppy Roads",
        job: "Mobile App Developer",
        company: "Slack",
        bio: lorem,
        email: "heppyRds@gmail.com",
        phone: "+233 456 789 43",
        website: "heppy.website.com",
        pic: "https://i.pravatar.cc/400?img=26",
      },
      {
        name: "Rosewood Michaelson",
        job: "Apple Inc",
        company: "Slack",
        bio: lorem,
        email: "SoulayRay@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=10",
      },
      {
        name: "Harry Bridgeton",
        job: "Frontend Developer",
        company: "Microsoft",
        bio: lorem,
        email: "fabilaal@gmail.com",
        phone: "+233 456 789 43",
        website: "sam.website.com",
        pic: "https://i.pravatar.cc/400?img=5",
      },
    ],
  },
];
